// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Birane Diaw's public profile: name, headline, education, and focus areas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Birane Diaw",
          signature: "B. DIAW",
          headline: "Engineering student focused on industrial automation, functional safety, energy systems, digital twins, and RF/space electronics.",
          languages: ["English", "French", "Arabic"],
          focus_areas: [
            "Automation & Industrial Safety",
            "Energy & Smart Grids",
            "Digital Twins & AI",
            "Electronics / RF / Space"
          ]
        })
      }
    ]
  })
});

// src/lib/mcp/tools/list-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var CATEGORIES = [
  "Automation & Industrial Safety",
  "Energy & Smart Grids",
  "Digital Twins & AI",
  "Electronics / RF / Space"
];
var SKILLS = {
  "Automation & Industrial Safety": [
    "TIA Portal",
    "Codesys 3.5",
    "GRAFCET IEC 60848",
    "IEC 61511",
    "SCL",
    "LADDER",
    "ST"
  ],
  "Energy & Smart Grids": ["Power systems", "Smart grid simulation", "Li-ion battery modeling"],
  "Digital Twins & AI": ["Python", "Streamlit", "Machine learning", "Simulation"],
  "Electronics / RF / Space": ["PCB design", "RF systems", "Radar", "Flight control"]
};
var list_skills_default = defineTool2({
  name: "list_skills",
  title: "List technical skills",
  description: "Return Birane Diaw's technical skills, optionally filtered by category.",
  inputSchema: {
    category: z.enum(CATEGORIES).optional().describe("Optional category to filter skills by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const payload = category ? { [category]: SKILLS[category] } : SKILLS;
    return { content: [{ type: "text", text: JSON.stringify(payload) }] };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var CATEGORIES2 = [
  "Automation & Industrial Safety",
  "Energy & Smart Grids",
  "Digital Twins & AI",
  "Electronics / RF / Space"
];
var PROJECTS = [
  {
    title: "AS/RS Codesys",
    category: "Automation & Industrial Safety",
    summary: "Automated storage/retrieval system programmed in Codesys 3.5 with ST and GRAFCET.",
    tags: ["Codesys", "ST", "GRAFCET"],
    link: "https://github.com/"
  },
  {
    title: "Li-ion Battery Digital Twin",
    category: "Digital Twins & AI",
    summary: "Live Streamlit digital twin of a Li-ion battery cell with state estimation.",
    tags: ["Python", "Streamlit", "Simulation"]
  },
  {
    title: "B747 Flight Controller",
    category: "Electronics / RF / Space",
    summary: "Longitudinal flight control design and simulation for a Boeing 747 model.",
    tags: ["Control", "MATLAB", "Aerospace"]
  },
  {
    title: "Airport Radar PCB",
    category: "Electronics / RF / Space",
    summary: "RF front-end and PCB design for an airport primary surveillance radar demo.",
    tags: ["RF", "PCB", "Radar"]
  }
];
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "Return Birane Diaw's engineering projects, optionally filtered by category.",
  inputSchema: {
    category: z2.enum(CATEGORIES2).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? PROJECTS.filter((p) => p.category === category) : PROJECTS;
    return { content: [{ type: "text", text: JSON.stringify(items) }] };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_testimonials_default = defineTool4({
  name: "list_testimonials",
  title: "List testimonials",
  description: "Return public testimonials left on Birane Diaw's portfolio.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max number of testimonials to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const env = globalThis.process?.env ?? {};
    const url = env.SUPABASE_URL;
    const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("testimonials").select("first_name,last_name,title,message,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "birane-diaw-portfolio",
  title: "Birane Diaw Portfolio",
  version: "0.1.0",
  instructions: "Public tools for Birane Diaw's engineering portfolio. Use get_profile for a bio, list_skills and list_projects (optionally filtered by category) for technical work, and list_testimonials for public feedback.",
  tools: [get_profile_default, list_skills_default, list_projects_default, list_testimonials_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
